### ISSUE TITLE
网页字体使用

### ISSUE THREAD

**Issue by roojay** [roojay520/Notes#1]
* 微软应用商店使用的字体:
'Segoe UI',SegoeUI,'Microsoft YaHei',微软雅黑,"Helvetica Neue",Helvetica,Arial,sans-serif

* 思源字体族: 
Google 将思源字体归入旗下 Noto 字体家族，因此思源黑体的名字为 Noto Sans CJK，思源宋体的名字为 Noto Serif CJK；Adobe 将思源字体归入旗下 Source 字体家族，因此思源黑体的名字为 Source Han Sans，思源宋体的名字为 Source Han Serif。

* 网页字体设置最佳实践
```css
body {
  font-family: -apple-system, BlinkMacSystemFont, "PingFang SC","Helvetica Neue",STHeiti,"Microsoft Yahei",Tahoma,Simsun,sans-serif;
}
```
