### ISSUE TITLE
文字对齐排版

### ISSUE THREAD

**Issue by roojay520** [roojay520/Notes#16]
```CSS
.text {
   color: #313131;
   text-align: justify;
   text-align-last: justify;
   text-justify: distribute;
   text-align-last: initial;
}
```
