### ISSUE TITLE
更改浏览器输入框提示文字样式

### ISSUE THREAD

**Issue by roojay520** [roojay520/Notes#17]
```css
input::-webkit-input-placeholder {  /* WebKit browsers */
    font-size: 1.125rem;
    color: gray;
}
input:-moz-placeholder { /* Mozilla Firefox 4 to 18 */
    font-size: 1.125rem;
    color: gray;
}
input::-moz-placeholder { /* Mozilla Firefox 19+ */
    font-size: 1.125rem;
    color: gray;
}
input :-ms-input-placeholder { /* Internet Explorer 10+ */
    font-size: 1.125rem;
    color: gray;
}
```
