### ISSUE TITLE
Github Actions 根据提交消息判断是否执行

### ISSUE THREAD

**Issue by roojay** [roojay520/Notes#37]
- 特定短语跳过执行
```yml
jobs:
  format:
    runs-on: ubuntu-latest
    if: "! contains(github.event.head_commit.message, 'wip')"
```
- 特定短语触发执行
```yml
jobs:
  format:
    runs-on: ubuntu-latest
    if: "contains(github.event.head_commit.message, '[build]')"
```

原文链接：[Running GitHub Actions for Certain Commit Messages](https://ryangjchandler.co.uk/articles/running-github-actions-for-certain-commit-messages)
